
phases:
  pre_build:
    commands:
      - echo Logging into ECR
      - aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username project3user --password-stdin 992180240141.dkr.ecr.us-east-1.amazonaws.com/coworking-app
